In [2]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
# MultinomiaNB 多项式朴素贝叶斯，BernoulliNB 伯努利朴素贝叶斯，GaussianNB 高斯朴素贝叶斯 
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB

In [16]:
iris = datasets.load_iris()
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target)
# print(iris)
# print((x_test))
# print((y_test))

[[6.3 2.5 5.  1.9]
 [5.7 3.  4.2 1.2]
 [5.  3.5 1.3 0.3]
 [5.  3.  1.6 0.2]
 [5.1 3.8 1.9 0.4]
 [6.8 3.2 5.9 2.3]
 [6.3 3.3 6.  2.5]
 [5.8 4.  1.2 0.2]
 [6.3 2.8 5.1 1.5]
 [6.7 3.3 5.7 2.5]
 [5.9 3.2 4.8 1.8]
 [4.9 3.1 1.5 0.1]
 [6.6 3.  4.4 1.4]
 [5.6 2.7 4.2 1.3]
 [6.2 3.4 5.4 2.3]
 [6.7 3.1 4.4 1.4]
 [4.4 2.9 1.4 0.2]
 [5.7 2.9 4.2 1.3]
 [5.8 2.7 5.1 1.9]
 [5.1 3.8 1.5 0.3]
 [6.3 2.7 4.9 1.8]
 [6.8 2.8 4.8 1.4]
 [5.4 3.9 1.7 0.4]
 [6.1 3.  4.9 1.8]
 [5.2 3.4 1.4 0.2]
 [5.1 3.8 1.6 0.2]
 [4.4 3.2 1.3 0.2]
 [6.1 2.8 4.7 1.2]
 [6.3 3.4 5.6 2.4]
 [5.7 2.8 4.5 1.3]
 [5.  3.2 1.2 0.2]
 [5.1 3.7 1.5 0.4]
 [5.9 3.  5.1 1.8]
 [5.8 2.7 5.1 1.9]
 [6.3 2.3 4.4 1.3]
 [5.  3.6 1.4 0.2]
 [5.  3.3 1.4 0.2]
 [6.3 2.9 5.6 1.8]]
[2 1 0 0 0 2 2 0 2 2 1 0 1 1 2 1 0 1 2 0 2 1 0 2 0 0 0 1 2 1 0 0 2 2 1 0 0
 2]


In [10]:
# 使用高斯朴素贝叶斯进行训练
gaussian_nb = GaussianNB()
gaussian_nb.fit(x_train,y_train)

# 使用多项式朴树贝叶斯进行训练
mul_nb = MultinomialNB()
mul_nb.fit(x_train,y_train)

# 使用伯努利朴素贝叶斯进行训练
bern_nb = BernoulliNB()
bern_nb.fit(x_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [7]:
print(classification_report(gaussian_nb.predict(x_test),y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       1.00      1.00      1.00        16
          2       1.00      1.00      1.00        13

avg / total       1.00      1.00      1.00        38



In [9]:
print(classification_report(mul_nb.predict(x_test),y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         9
          1       0.62      1.00      0.77        10
          2       1.00      0.68      0.81        19

avg / total       0.90      0.84      0.85        38



In [11]:
print(classification_report(bern_nb.predict(x_test),y_test))

             precision    recall  f1-score   support

          0       1.00      0.24      0.38        38
          1       0.00      0.00      0.00         0
          2       0.00      0.00      0.00         0

avg / total       1.00      0.24      0.38        38



D:\install\anaconda\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
