In [1]:
import numpy as np

In [2]:
arr1 = np.arange(2,14)
print(arr1)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [3]:
print(arr1[2])

4


In [7]:
print(arr1[1:4])

[3 4 5]


In [8]:
print(arr1[1:-1]) # 取第二个元素到倒数第一个元素，不包括最后一个元素

[ 3  4  5  6  7  8  9 10 11 12]


In [9]:
print(arr1[:5]) # 取前5个元素

[2 3 4 5 6]


In [11]:
print(arr1[1:])
print(arr1[-2:]) # 取最后两个元素

[ 3  4  5  6  7  8  9 10 11 12 13]
[12 13]


In [13]:
arr2 = arr1.reshape(3,4)
print(arr2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [14]:
print(arr2[0]) # 第一行
print(arr2[1]) # 第二行

[2 3 4 5]
[6 7 8 9]


In [16]:
print(arr2[1][1]) # 第二行，第二个元素
print(arr2[1,1])  # 同上

7
7


In [17]:
print(arr2[:,2]) # 提取所有行里的第二列

[ 4  8 12]


In [19]:
# 迭代每一行数据
for i in arr2:  
    print(i)

[2 3 4 5]
[6 7 8 9]
[10 11 12 13]


In [20]:
# 迭代每一列，先转置，在迭代矩阵
for i in arr2.T:
    print(i)

[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]


In [21]:
# 迭代每一个元素
for i in arr2.flat:
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
