In [1]:
import numpy as np

In [5]:
arr1 = np.array([1,2,4])
arr2 = np.array([4,5,6])

In [6]:
# 垂直合并，可以进行多个array的合并
arr3 = np.vstack((arr1,arr2))  
print(arr3)
print(arr3.shape)

[[1 2 4]
 [4 5 6]]
(2, 3)


In [7]:
# 水平合并，可以进行多个array的合并
arr4 = np.hstack((arr1,arr2))
print(arr4)

[1 2 4 4 5 6]


In [21]:
arr5 = np.concatenate((arr3,arr3),axis=0)  # 形状必须相同，axis=0代表纵向拼接
print(arr5)

[[1 2 4]
 [4 5 6]
 [1 2 4]
 [4 5 6]]


In [22]:
arr6 = np.concatenate((arr3,arr3),axis=1) # 形状必须相同，axis=1代表横向拼接
print(arr6)


[[1 2 4 1 2 4]
 [4 5 6 4 5 6]]


In [24]:
print(arr1.T) # 一维的array 不嫩转置
print(arr1.shape)

[1 2 4]
(3,)


In [26]:
arr_1 = arr1[np.newaxis,:]
print(arr_1)
print(arr_1.shape)

[[1 2 4]]
(1, 3)


In [27]:
print(arr_1.T)

[[1]
 [2]
 [4]]


In [29]:
arr_2 = arr1[:,np.newaxis]
print(arr_2)
print(arr_2.shape)

[[1]
 [2]
 [4]]
(3, 1)


In [31]:
arr1_3 = np.atleast_2d(arr1) # 将不是2维的array转换为2维，2维或多维的不转换
print(arr1_3)
print(arr1_3.T)
print(arr1.ndim)
print(arr1_3.ndim)

[[1 2 4]]
[[1]
 [2]
 [4]]
1
2
